title: Oliver Newman
email: oliver@whmsi.com
description: > 
  Oliver Newman is a computer science major at Swarthmore College pursuing a
  career in software engineering.
url: "https://www.onewman.com" # the base hostname & protocol site
github_username: oliver-newman

sass:
  sass_dir: _scss
  style: :compressed
